-keep class com.streamapp.models.** { *; }
-keep class com.streamapp.api.** { *; }
-keepattributes Signature
-keepattributes *Annotation*
-dontwarn okhttp3.**
-dontwarn retrofit2.**
-keep class retrofit2.** { *; }
-keep class com.bumptech.glide.** { *; }
